1:
	#making exercise 1
	gcc *exercise_1.c -o exec_1
2:
	#making exercise 2
	gcc *exercise_2.c -o exec_2
3_1:
	#making exercise 3 part 1 -- exercise 1 with stdin
	gcc *exercise_3_1.c -o exec_3_1
3_2:
	#making exercise 3 part 2 -- exercise 2 with stdin
	gcc *exercise_3_2.c -o exec_3_2
4:
	#making exercise 4 -- sum of structs
	gcc *exercise_4.c -o exec_4
